# Generated by Django 3.0.3 on 2020-02-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('points', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
